---
  - name: install nginx
    action: apt name=nginx
    sudo: True

  - name: write nginx.conf
    action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    sudo: True
    notify:
      - restart nginx

  - name: Create jobs folder
    sudo: True
    action: file path={{source_path}} state=directory

  - name: Clone the repo in the source folder
    git: repo=git://github.com/RuralIndia/pari.git dest={{source_path}}
    sudo: True