---
# file: roles/common/tasks/main.yml

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: apt
  sudo: yes

- name: install build essentials
  apt: name=$item state=installed
  with_items:
    - autoconf
    - binutils-doc
    - bison
    - build-essential
    - flex
  sudo: yes

- name: install git
  apt: name=git state=latest
  sudo: yes

#- name: Installing npm
#  npm: name=less global=yes state=present
#  sudo: True


- name: install essential packages
  apt: name=$item state=installed
  with_items:
    - libjpeg-dev
    - libpng-dev
    - libxml2-dev
    - libxslt1-dev
    - libmemcached-dev
  sudo: True